// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `logicedbgctrlif.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <log_ice_dbg/ice/logicedbgctrlif.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __logicedbg__sqlitectrl__SetDbName_name = "SetDbName";

static const ::std::string __logicedbg__sqlitectrl__Enable_name = "Enable";

::Ice::Object* IceInternal::upCast(::logicedbg::sqlitectrl* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::logicedbg::sqlitectrl* p) { return p; }

void
logicedbg::__read(::IceInternal::BasicStream* __is, ::logicedbg::sqlitectrlPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::logicedbg::sqlitectrl;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::logicedbg::sqlitectrl::SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::logicedbg::sqlitectrl* __del = dynamic_cast< ::IceDelegate::logicedbg::sqlitectrl*>(__delBase.get());
            __del->SetDbName(s, inmem, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::logicedbg::sqlitectrl::begin_SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __logicedbg__sqlitectrl__SetDbName_name, __del, __cookie);
    try
    {
        __result->__prepare(__logicedbg__sqlitectrl__SetDbName_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(s);
        __os->write(inmem);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::logicedbg::sqlitectrl::end_SetDbName(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __logicedbg__sqlitectrl__SetDbName_name);
}

void
IceProxy::logicedbg::sqlitectrl::Enable(bool val, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::logicedbg::sqlitectrl* __del = dynamic_cast< ::IceDelegate::logicedbg::sqlitectrl*>(__delBase.get());
            __del->Enable(val, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::logicedbg::sqlitectrl::begin_Enable(bool val, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __logicedbg__sqlitectrl__Enable_name, __del, __cookie);
    try
    {
        __result->__prepare(__logicedbg__sqlitectrl__Enable_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(val);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::logicedbg::sqlitectrl::end_Enable(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __logicedbg__sqlitectrl__Enable_name);
}

const ::std::string&
IceProxy::logicedbg::sqlitectrl::ice_staticId()
{
    return ::logicedbg::sqlitectrl::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::logicedbg::sqlitectrl::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::logicedbg::sqlitectrl);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::logicedbg::sqlitectrl::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::logicedbg::sqlitectrl);
}

::IceProxy::Ice::Object*
IceProxy::logicedbg::sqlitectrl::__newInstance() const
{
    return new sqlitectrl;
}

void
IceDelegateM::logicedbg::sqlitectrl::SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __logicedbg__sqlitectrl__SetDbName_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(s);
        __os->write(inmem);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::logicedbg::sqlitectrl::Enable(bool val, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __logicedbg__sqlitectrl__Enable_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(val);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::logicedbg::sqlitectrl::SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& s, bool inmem, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_s(s),
            _m_inmem(inmem)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::logicedbg::sqlitectrl* servant = dynamic_cast< ::logicedbg::sqlitectrl*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->SetDbName(_m_s, _m_inmem, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_s;
        bool _m_inmem;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __logicedbg__sqlitectrl__SetDbName_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(s, inmem, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::logicedbg::sqlitectrl::Enable(bool val, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool val, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_val(val)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::logicedbg::sqlitectrl* servant = dynamic_cast< ::logicedbg::sqlitectrl*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->Enable(_m_val, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool _m_val;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __logicedbg__sqlitectrl__Enable_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(val, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::ObjectPtr
logicedbg::sqlitectrl::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __logicedbg__sqlitectrl_ids[2] =
{
    "::Ice::Object",
    "::logicedbg::sqlitectrl"
};

bool
logicedbg::sqlitectrl::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__logicedbg__sqlitectrl_ids, __logicedbg__sqlitectrl_ids + 2, _s);
}

::std::vector< ::std::string>
logicedbg::sqlitectrl::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__logicedbg__sqlitectrl_ids[0], &__logicedbg__sqlitectrl_ids[2]);
}

const ::std::string&
logicedbg::sqlitectrl::ice_id(const ::Ice::Current&) const
{
    return __logicedbg__sqlitectrl_ids[1];
}

const ::std::string&
logicedbg::sqlitectrl::ice_staticId()
{
    return __logicedbg__sqlitectrl_ids[1];
}

::Ice::DispatchStatus
logicedbg::sqlitectrl::___SetDbName(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::std::string s;
    bool inmem;
    __is->read(s);
    __is->read(inmem);
    __is->endReadEncaps();
    SetDbName(s, inmem, __current);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
logicedbg::sqlitectrl::___Enable(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    bool val;
    __is->read(val);
    __is->endReadEncaps();
    Enable(val, __current);
    return ::Ice::DispatchOK;
}

static ::std::string __logicedbg__sqlitectrl_all[] =
{
    "Enable",
    "SetDbName",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

::Ice::DispatchStatus
logicedbg::sqlitectrl::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__logicedbg__sqlitectrl_all, __logicedbg__sqlitectrl_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __logicedbg__sqlitectrl_all)
    {
        case 0:
        {
            return ___Enable(in, current);
        }
        case 1:
        {
            return ___SetDbName(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
logicedbg::sqlitectrl::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
logicedbg::sqlitectrl::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
logicedbg::sqlitectrl::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type logicedbg::sqlitectrl was not generated with stream support";
    throw ex;
}

void
logicedbg::sqlitectrl::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type logicedbg::sqlitectrl was not generated with stream support";
    throw ex;
}
#endif

void 
logicedbg::__patch__sqlitectrlPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::logicedbg::sqlitectrlPtr* p = static_cast< ::logicedbg::sqlitectrlPtr*>(__addr);
    assert(p);
    *p = ::logicedbg::sqlitectrlPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::logicedbg::sqlitectrl::ice_staticId(), v->ice_id());
    }
}
