// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `logicedbgctrlif.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __log_ice_dbg_ice_clean_slice___logicedbgctrlif_h__
#define __log_ice_dbg_ice_clean_slice___logicedbgctrlif_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace logicedbg
{

class sqlitectrl;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::logicedbg::sqlitectrl>&);
::IceProxy::Ice::Object* upCast(::IceProxy::logicedbg::sqlitectrl*);

}

}

namespace logicedbg
{

class sqlitectrl;
bool operator==(const sqlitectrl&, const sqlitectrl&);
bool operator<(const sqlitectrl&, const sqlitectrl&);
::Ice::Object* upCast(::logicedbg::sqlitectrl*);
typedef ::IceInternal::Handle< ::logicedbg::sqlitectrl> sqlitectrlPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::logicedbg::sqlitectrl> sqlitectrlPrx;
void __patch(sqlitectrlPtr&, const ::Ice::ObjectPtr&);

}

namespace logicedbg
{

class Callback_sqlitectrl_SetDbName_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_sqlitectrl_SetDbName_Base> Callback_sqlitectrl_SetDbNamePtr;

class Callback_sqlitectrl_Enable_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_sqlitectrl_Enable_Base> Callback_sqlitectrl_EnablePtr;

}

namespace IceProxy
{

namespace logicedbg
{

class sqlitectrl : virtual public ::IceProxy::Ice::Object
{
public:

    void SetDbName(const ::std::string& s, bool inmem)
    {
        SetDbName(s, inmem, 0);
    }
    void SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context& __ctx)
    {
        SetDbName(s, inmem, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_SetDbName(const ::std::string& s, bool inmem, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_SetDbName(s, inmem, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_SetDbName(const ::std::string& s, bool inmem, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_SetDbName(s, inmem, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_SetDbName(s, inmem, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_SetDbName(s, inmem, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_SetDbName(const ::std::string& s, bool inmem)
    {
        return begin_SetDbName(s, inmem, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context& __ctx)
    {
        return begin_SetDbName(s, inmem, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SetDbName(const ::std::string& s, bool inmem, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetDbName(s, inmem, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetDbName(s, inmem, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetDbName(const ::std::string& s, bool inmem, const ::logicedbg::Callback_sqlitectrl_SetDbNamePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetDbName(s, inmem, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetDbName(const ::std::string& s, bool inmem, const ::Ice::Context& __ctx, const ::logicedbg::Callback_sqlitectrl_SetDbNamePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetDbName(s, inmem, &__ctx, __del, __cookie);
    }

    void end_SetDbName(const ::Ice::AsyncResultPtr&);
    
private:

    void SetDbName(const ::std::string&, bool, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_SetDbName(const ::std::string&, bool, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void Enable(bool val)
    {
        Enable(val, 0);
    }
    void Enable(bool val, const ::Ice::Context& __ctx)
    {
        Enable(val, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_Enable(bool val, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_Enable(val, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_Enable(bool val, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_Enable(val, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_Enable(bool val, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_Enable(val, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_Enable(bool val, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_Enable(val, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_Enable(bool val)
    {
        return begin_Enable(val, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Enable(bool val, const ::Ice::Context& __ctx)
    {
        return begin_Enable(val, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Enable(bool val, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Enable(val, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Enable(bool val, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Enable(val, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Enable(bool val, const ::logicedbg::Callback_sqlitectrl_EnablePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Enable(val, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Enable(bool val, const ::Ice::Context& __ctx, const ::logicedbg::Callback_sqlitectrl_EnablePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Enable(val, &__ctx, __del, __cookie);
    }

    void end_Enable(const ::Ice::AsyncResultPtr&);
    
private:

    void Enable(bool, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_Enable(bool, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_secure(bool __secure) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_twoway() const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_oneway() const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_batchOneway() const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_datagram() const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_batchDatagram() const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_compress(bool __compress) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_timeout(int __timeout) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<sqlitectrl> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<sqlitectrl*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace logicedbg
{

class sqlitectrl : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void SetDbName(const ::std::string&, bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void Enable(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace logicedbg
{

class sqlitectrl : virtual public ::IceDelegate::logicedbg::sqlitectrl,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void SetDbName(const ::std::string&, bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void Enable(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace logicedbg
{

class sqlitectrl : virtual public ::IceDelegate::logicedbg::sqlitectrl,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void SetDbName(const ::std::string&, bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void Enable(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace logicedbg
{

class sqlitectrl : virtual public ::Ice::Object
{
public:

    typedef sqlitectrlPrx ProxyType;
    typedef sqlitectrlPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void SetDbName(const ::std::string&, bool, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___SetDbName(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void Enable(bool, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___Enable(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const sqlitectrl& l, const sqlitectrl& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const sqlitectrl& l, const sqlitectrl& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace logicedbg
{

template<class T>
class CallbackNC_sqlitectrl_SetDbName : public Callback_sqlitectrl_SetDbName_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_sqlitectrl_SetDbName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_sqlitectrl_SetDbNamePtr
newCallback_sqlitectrl_SetDbName(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_sqlitectrl_SetDbName<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_sqlitectrl_SetDbNamePtr
newCallback_sqlitectrl_SetDbName(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_sqlitectrl_SetDbName<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_sqlitectrl_SetDbNamePtr
newCallback_sqlitectrl_SetDbName(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_sqlitectrl_SetDbName<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_sqlitectrl_SetDbNamePtr
newCallback_sqlitectrl_SetDbName(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_sqlitectrl_SetDbName<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_sqlitectrl_SetDbName : public Callback_sqlitectrl_SetDbName_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_sqlitectrl_SetDbName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_sqlitectrl_SetDbNamePtr
newCallback_sqlitectrl_SetDbName(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_sqlitectrl_SetDbName<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_sqlitectrl_SetDbNamePtr
newCallback_sqlitectrl_SetDbName(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_sqlitectrl_SetDbName<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_sqlitectrl_SetDbNamePtr
newCallback_sqlitectrl_SetDbName(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_sqlitectrl_SetDbName<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_sqlitectrl_SetDbNamePtr
newCallback_sqlitectrl_SetDbName(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_sqlitectrl_SetDbName<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_sqlitectrl_Enable : public Callback_sqlitectrl_Enable_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_sqlitectrl_Enable(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_sqlitectrl_EnablePtr
newCallback_sqlitectrl_Enable(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_sqlitectrl_Enable<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_sqlitectrl_EnablePtr
newCallback_sqlitectrl_Enable(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_sqlitectrl_Enable<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_sqlitectrl_EnablePtr
newCallback_sqlitectrl_Enable(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_sqlitectrl_Enable<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_sqlitectrl_EnablePtr
newCallback_sqlitectrl_Enable(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_sqlitectrl_Enable<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_sqlitectrl_Enable : public Callback_sqlitectrl_Enable_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_sqlitectrl_Enable(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_sqlitectrl_EnablePtr
newCallback_sqlitectrl_Enable(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_sqlitectrl_Enable<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_sqlitectrl_EnablePtr
newCallback_sqlitectrl_Enable(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_sqlitectrl_Enable<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_sqlitectrl_EnablePtr
newCallback_sqlitectrl_Enable(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_sqlitectrl_Enable<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_sqlitectrl_EnablePtr
newCallback_sqlitectrl_Enable(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_sqlitectrl_Enable<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
