// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `loggerctrl.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __log_ice_ice_clean_slice___loggerctrl_h__
#define __log_ice_ice_clean_slice___loggerctrl_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef LOG_ICE_API
#   ifdef LOG_ICE_API_EXPORTS
#       define LOG_ICE_API ICE_DECLSPEC_EXPORT
#   else
#       define LOG_ICE_API ICE_DECLSPEC_IMPORT
#   endif
#endif

namespace IceProxy
{

namespace loggerice
{

class loggerctrl;
LOG_ICE_API void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::loggerice::loggerctrl>&);
LOG_ICE_API ::IceProxy::Ice::Object* upCast(::IceProxy::loggerice::loggerctrl*);

}

}

namespace loggerice
{

class loggerctrl;
bool operator==(const loggerctrl&, const loggerctrl&);
bool operator<(const loggerctrl&, const loggerctrl&);
LOG_ICE_API ::Ice::Object* upCast(::loggerice::loggerctrl*);
typedef ::IceInternal::Handle< ::loggerice::loggerctrl> loggerctrlPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::loggerice::loggerctrl> loggerctrlPrx;
LOG_ICE_API void __patch(loggerctrlPtr&, const ::Ice::ObjectPtr&);

}

namespace loggerice
{

class Callback_loggerctrl_Register_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_loggerctrl_Register_Base> Callback_loggerctrl_RegisterPtr;

class Callback_loggerctrl_SetName_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_loggerctrl_SetName_Base> Callback_loggerctrl_SetNamePtr;

class Callback_loggerctrl_SetThreadName_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_loggerctrl_SetThreadName_Base> Callback_loggerctrl_SetThreadNamePtr;

}

namespace IceProxy
{

namespace loggerice
{

class loggerctrl : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::Int Register(const ::std::string& name)
    {
        return Register(name, 0);
    }
    ::Ice::Int Register(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return Register(name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_Register(const ::std::string& name, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_Register(name, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_Register(const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_Register(name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_Register(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_Register(name, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_Register(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_Register(name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_Register(const ::std::string& name, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::loggerice::loggerctrlPrx __proxy = ::loggerice::loggerctrlPrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_Register(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_Register(name, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_Register(const ::std::string& name)
    {
        return begin_Register(name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Register(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_Register(name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Register(const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Register(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Register(const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Register(name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Register(const ::std::string& name, const ::loggerice::Callback_loggerctrl_RegisterPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Register(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Register(const ::std::string& name, const ::Ice::Context& __ctx, const ::loggerice::Callback_loggerctrl_RegisterPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Register(name, &__ctx, __del, __cookie);
    }

    LOG_ICE_API ::Ice::Int end_Register(const ::Ice::AsyncResultPtr&);
    
private:

    LOG_ICE_API ::Ice::Int Register(const ::std::string&, const ::Ice::Context*);
    LOG_ICE_API ::Ice::AsyncResultPtr begin_Register(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void SetName(::Ice::Int id, const ::std::string& name)
    {
        SetName(id, name, 0);
    }
    void SetName(::Ice::Int id, const ::std::string& name, const ::Ice::Context& __ctx)
    {
        SetName(id, name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_SetName(::Ice::Int id, const ::std::string& name, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_SetName(id, name, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_SetName(::Ice::Int id, const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_SetName(id, name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_SetName(::Ice::Int id, const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_SetName(id, name, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_SetName(::Ice::Int id, const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_SetName(id, name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_SetName(::Ice::Int id, const ::std::string& name)
    {
        return begin_SetName(id, name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SetName(::Ice::Int id, const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_SetName(id, name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SetName(::Ice::Int id, const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetName(id, name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetName(::Ice::Int id, const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetName(id, name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetName(::Ice::Int id, const ::std::string& name, const ::loggerice::Callback_loggerctrl_SetNamePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetName(id, name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetName(::Ice::Int id, const ::std::string& name, const ::Ice::Context& __ctx, const ::loggerice::Callback_loggerctrl_SetNamePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetName(id, name, &__ctx, __del, __cookie);
    }

    LOG_ICE_API void end_SetName(const ::Ice::AsyncResultPtr&);
    
private:

    LOG_ICE_API void SetName(::Ice::Int, const ::std::string&, const ::Ice::Context*);
    LOG_ICE_API ::Ice::AsyncResultPtr begin_SetName(::Ice::Int, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name)
    {
        SetThreadName(regid, threadid, name, 0);
    }
    void SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::Ice::Context& __ctx)
    {
        SetThreadName(regid, threadid, name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_SetThreadName(regid, threadid, name, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_SetThreadName(regid, threadid, name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_SetThreadName(regid, threadid, name, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_SetThreadName(regid, threadid, name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name)
    {
        return begin_SetThreadName(regid, threadid, name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_SetThreadName(regid, threadid, name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetThreadName(regid, threadid, name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetThreadName(regid, threadid, name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::loggerice::Callback_loggerctrl_SetThreadNamePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetThreadName(regid, threadid, name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SetThreadName(::Ice::Int regid, ::Ice::Long threadid, const ::std::string& name, const ::Ice::Context& __ctx, const ::loggerice::Callback_loggerctrl_SetThreadNamePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SetThreadName(regid, threadid, name, &__ctx, __del, __cookie);
    }

    LOG_ICE_API void end_SetThreadName(const ::Ice::AsyncResultPtr&);
    
private:

    LOG_ICE_API void SetThreadName(::Ice::Int, ::Ice::Long, const ::std::string&, const ::Ice::Context*);
    LOG_ICE_API ::Ice::AsyncResultPtr begin_SetThreadName(::Ice::Int, ::Ice::Long, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_secure(bool __secure) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_twoway() const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_oneway() const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_batchOneway() const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_datagram() const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_batchDatagram() const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_compress(bool __compress) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_timeout(int __timeout) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<loggerctrl> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<loggerctrl*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    LOG_ICE_API static const ::std::string& ice_staticId();

private: 

    LOG_ICE_API virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    LOG_ICE_API virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    LOG_ICE_API virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace loggerice
{

class LOG_ICE_API loggerctrl : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Ice::Int Register(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void SetName(::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void SetThreadName(::Ice::Int, ::Ice::Long, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace loggerice
{

class LOG_ICE_API loggerctrl : virtual public ::IceDelegate::loggerice::loggerctrl,
                               virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Ice::Int Register(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void SetName(::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void SetThreadName(::Ice::Int, ::Ice::Long, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace loggerice
{

class LOG_ICE_API loggerctrl : virtual public ::IceDelegate::loggerice::loggerctrl,
                               virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Ice::Int Register(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void SetName(::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void SetThreadName(::Ice::Int, ::Ice::Long, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace loggerice
{

class LOG_ICE_API loggerctrl : virtual public ::Ice::Object
{
public:

    typedef loggerctrlPrx ProxyType;
    typedef loggerctrlPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Ice::Int Register(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___Register(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void SetName(::Ice::Int, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___SetName(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void SetThreadName(::Ice::Int, ::Ice::Long, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___SetThreadName(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const loggerctrl& l, const loggerctrl& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const loggerctrl& l, const loggerctrl& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace loggerice
{

template<class T>
class CallbackNC_loggerctrl_Register : public Callback_loggerctrl_Register_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_loggerctrl_Register(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::loggerice::loggerctrlPrx __proxy = ::loggerice::loggerctrlPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_Register(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_loggerctrl_RegisterPtr
newCallback_loggerctrl_Register(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_Register<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_loggerctrl_RegisterPtr
newCallback_loggerctrl_Register(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_Register<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_loggerctrl_Register : public Callback_loggerctrl_Register_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_loggerctrl_Register(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::loggerice::loggerctrlPrx __proxy = ::loggerice::loggerctrlPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_Register(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_loggerctrl_RegisterPtr
newCallback_loggerctrl_Register(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_Register<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_loggerctrl_RegisterPtr
newCallback_loggerctrl_Register(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_Register<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_loggerctrl_SetName : public Callback_loggerctrl_SetName_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_loggerctrl_SetName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_loggerctrl_SetNamePtr
newCallback_loggerctrl_SetName(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_SetName<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_loggerctrl_SetNamePtr
newCallback_loggerctrl_SetName(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_SetName<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_loggerctrl_SetNamePtr
newCallback_loggerctrl_SetName(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_SetName<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_loggerctrl_SetNamePtr
newCallback_loggerctrl_SetName(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_SetName<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_loggerctrl_SetName : public Callback_loggerctrl_SetName_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_loggerctrl_SetName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_loggerctrl_SetNamePtr
newCallback_loggerctrl_SetName(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_SetName<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_loggerctrl_SetNamePtr
newCallback_loggerctrl_SetName(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_SetName<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_loggerctrl_SetNamePtr
newCallback_loggerctrl_SetName(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_SetName<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_loggerctrl_SetNamePtr
newCallback_loggerctrl_SetName(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_SetName<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_loggerctrl_SetThreadName : public Callback_loggerctrl_SetThreadName_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_loggerctrl_SetThreadName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_loggerctrl_SetThreadNamePtr
newCallback_loggerctrl_SetThreadName(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_SetThreadName<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_loggerctrl_SetThreadNamePtr
newCallback_loggerctrl_SetThreadName(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_SetThreadName<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_loggerctrl_SetThreadNamePtr
newCallback_loggerctrl_SetThreadName(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_SetThreadName<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_loggerctrl_SetThreadNamePtr
newCallback_loggerctrl_SetThreadName(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_loggerctrl_SetThreadName<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_loggerctrl_SetThreadName : public Callback_loggerctrl_SetThreadName_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_loggerctrl_SetThreadName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_loggerctrl_SetThreadNamePtr
newCallback_loggerctrl_SetThreadName(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_SetThreadName<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_loggerctrl_SetThreadNamePtr
newCallback_loggerctrl_SetThreadName(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_SetThreadName<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_loggerctrl_SetThreadNamePtr
newCallback_loggerctrl_SetThreadName(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_SetThreadName<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_loggerctrl_SetThreadNamePtr
newCallback_loggerctrl_SetThreadName(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_loggerctrl_SetThreadName<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
