// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `option_event.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __log_ice_ice_clean_slice___option_event_h__
#define __log_ice_ice_clean_slice___option_event_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <log_ice/ice/event.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef LOG_ICE_API
#   ifdef LOG_ICE_API_EXPORTS
#       define LOG_ICE_API ICE_DECLSPEC_EXPORT
#   else
#       define LOG_ICE_API ICE_DECLSPEC_IMPORT
#   endif
#endif

namespace IceProxy
{

namespace loggerice
{

class optionevent;

class optioneventif;

}

}

namespace loggerice
{

class optionevent;
bool operator==(const optionevent&, const optionevent&);
bool operator<(const optionevent&, const optionevent&);

class optioneventif;
bool operator==(const optioneventif&, const optioneventif&);
bool operator<(const optioneventif&, const optioneventif&);

}

namespace IceInternal
{

LOG_ICE_API ::Ice::Object* upCast(::loggerice::optionevent*);
LOG_ICE_API ::IceProxy::Ice::Object* upCast(::IceProxy::loggerice::optionevent*);

LOG_ICE_API ::Ice::Object* upCast(::loggerice::optioneventif*);
LOG_ICE_API ::IceProxy::Ice::Object* upCast(::IceProxy::loggerice::optioneventif*);

}

namespace loggerice
{

typedef ::IceInternal::Handle< ::loggerice::optionevent> optioneventPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::loggerice::optionevent> optioneventPrx;

LOG_ICE_API void __read(::IceInternal::BasicStream*, optioneventPrx&);
LOG_ICE_API void __patch__optioneventPtr(void*, ::Ice::ObjectPtr&);

typedef ::IceInternal::Handle< ::loggerice::optioneventif> optioneventifPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::loggerice::optioneventif> optioneventifPrx;

LOG_ICE_API void __read(::IceInternal::BasicStream*, optioneventifPrx&);
LOG_ICE_API void __patch__optioneventifPtr(void*, ::Ice::ObjectPtr&);

}

namespace loggerice
{

class Callback_optioneventif_sendevent_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_optioneventif_sendevent_Base> Callback_optioneventif_sendeventPtr;

}

namespace IceProxy
{

namespace loggerice
{

class optionevent : virtual public ::IceProxy::loggerice::event
{
public:
    
    ::IceInternal::ProxyHandle<optionevent> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optionevent> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optionevent*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<optionevent*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    LOG_ICE_API static const ::std::string& ice_staticId();

private: 

    LOG_ICE_API virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    LOG_ICE_API virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    LOG_ICE_API virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class optioneventif : virtual public ::IceProxy::Ice::Object
{
public:

    void sendevent(const ::loggerice::optioneventPtr& theevent)
    {
        sendevent(theevent, 0);
    }
    void sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::Context& __ctx)
    {
        sendevent(theevent, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_sendevent(const ::loggerice::optioneventPtr& theevent)
    {
        return begin_sendevent(theevent, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::Context& __ctx)
    {
        return begin_sendevent(theevent, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendevent(theevent, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendevent(theevent, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendevent(const ::loggerice::optioneventPtr& theevent, const ::loggerice::Callback_optioneventif_sendeventPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendevent(theevent, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::Context& __ctx, const ::loggerice::Callback_optioneventif_sendeventPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendevent(theevent, &__ctx, __del, __cookie);
    }

    LOG_ICE_API void end_sendevent(const ::Ice::AsyncResultPtr&);
    
private:

    LOG_ICE_API void sendevent(const ::loggerice::optioneventPtr&, const ::Ice::Context*);
    LOG_ICE_API ::Ice::AsyncResultPtr begin_sendevent(const ::loggerice::optioneventPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<optioneventif> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<optioneventif> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<optioneventif*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<optioneventif*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    LOG_ICE_API static const ::std::string& ice_staticId();

private: 

    LOG_ICE_API virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    LOG_ICE_API virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    LOG_ICE_API virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace loggerice
{

class LOG_ICE_API optionevent : virtual public ::IceDelegate::loggerice::event
{
public:
};

class LOG_ICE_API optioneventif : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void sendevent(const ::loggerice::optioneventPtr&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace loggerice
{

class LOG_ICE_API optionevent : virtual public ::IceDelegate::loggerice::optionevent,
                                virtual public ::IceDelegateM::loggerice::event
{
public:
};

class LOG_ICE_API optioneventif : virtual public ::IceDelegate::loggerice::optioneventif,
                                  virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void sendevent(const ::loggerice::optioneventPtr&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace loggerice
{

class LOG_ICE_API optionevent : virtual public ::IceDelegate::loggerice::optionevent,
                                virtual public ::IceDelegateD::loggerice::event
{
public:
};

class LOG_ICE_API optioneventif : virtual public ::IceDelegate::loggerice::optioneventif,
                                  virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void sendevent(const ::loggerice::optioneventPtr&, const ::Ice::Context*);
};

}

}

namespace loggerice
{

class LOG_ICE_API optionevent : public ::loggerice::event
{
public:

    typedef optioneventPrx ProxyType;
    typedef optioneventPtr PointerType;
    
    optionevent() {}
    optionevent(::Ice::Int, ::Ice::Long, ::Ice::Int, ::Ice::Int, ::Ice::Int, ::Ice::Long, ::Ice::Long, ::Ice::Long, ::Ice::Int, ::Ice::Long, ::Ice::Long, const ::std::string&, const ::std::string&);
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();


    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif

    static const ::Ice::ObjectFactoryPtr& ice_factory();

protected:

    virtual ~optionevent() {}

    friend class optionevent__staticInit;

public:

    ::Ice::Long subType;

    ::Ice::Long value;

    ::std::string name;

    ::std::string strVal;
};

class optionevent__staticInit
{
public:

    ::loggerice::optionevent _init;
};

static optionevent__staticInit _optionevent_init;

inline bool operator==(const optionevent& l, const optionevent& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const optionevent& l, const optionevent& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class LOG_ICE_API optioneventif : virtual public ::Ice::Object
{
public:

    typedef optioneventifPrx ProxyType;
    typedef optioneventifPtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void sendevent(const ::loggerice::optioneventPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sendevent(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const optioneventif& l, const optioneventif& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const optioneventif& l, const optioneventif& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace loggerice
{

template<class T>
class CallbackNC_optioneventif_sendevent : public Callback_optioneventif_sendevent_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_optioneventif_sendevent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_optioneventif_sendeventPtr
newCallback_optioneventif_sendevent(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_optioneventif_sendevent<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_optioneventif_sendeventPtr
newCallback_optioneventif_sendevent(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_optioneventif_sendevent<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_optioneventif_sendeventPtr
newCallback_optioneventif_sendevent(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_optioneventif_sendevent<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_optioneventif_sendeventPtr
newCallback_optioneventif_sendevent(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_optioneventif_sendevent<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_optioneventif_sendevent : public Callback_optioneventif_sendevent_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_optioneventif_sendevent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_optioneventif_sendeventPtr
newCallback_optioneventif_sendevent(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_optioneventif_sendevent<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_optioneventif_sendeventPtr
newCallback_optioneventif_sendevent(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_optioneventif_sendevent<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_optioneventif_sendeventPtr
newCallback_optioneventif_sendevent(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_optioneventif_sendevent<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_optioneventif_sendeventPtr
newCallback_optioneventif_sendevent(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_optioneventif_sendevent<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
