// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `event.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __log_ice_ice_clean_slice___event_h__
#define __log_ice_ice_clean_slice___event_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef LOG_ICE_API
#   ifdef LOG_ICE_API_EXPORTS
#       define LOG_ICE_API ICE_DECLSPEC_EXPORT
#   else
#       define LOG_ICE_API ICE_DECLSPEC_IMPORT
#   endif
#endif

namespace IceProxy
{

namespace loggerice
{

class event;
LOG_ICE_API void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::loggerice::event>&);
LOG_ICE_API ::IceProxy::Ice::Object* upCast(::IceProxy::loggerice::event*);

}

}

namespace loggerice
{

class event;
bool operator==(const event&, const event&);
bool operator<(const event&, const event&);
LOG_ICE_API ::Ice::Object* upCast(::loggerice::event*);
typedef ::IceInternal::Handle< ::loggerice::event> eventPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::loggerice::event> eventPrx;
LOG_ICE_API void __patch(eventPtr&, const ::Ice::ObjectPtr&);

}

namespace loggerice
{

}

namespace IceProxy
{

namespace loggerice
{

class event : virtual public ::IceProxy::Ice::Object
{
public:
    
    ::IceInternal::ProxyHandle<event> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_secure(bool __secure) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_twoway() const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_oneway() const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_batchOneway() const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_datagram() const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_batchDatagram() const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_compress(bool __compress) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_timeout(int __timeout) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<event> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<event*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    LOG_ICE_API static const ::std::string& ice_staticId();

private: 

    LOG_ICE_API virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    LOG_ICE_API virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    LOG_ICE_API virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace loggerice
{

class LOG_ICE_API event : virtual public ::IceDelegate::Ice::Object
{
public:
};

}

}

namespace IceDelegateM
{

namespace loggerice
{

class LOG_ICE_API event : virtual public ::IceDelegate::loggerice::event,
                          virtual public ::IceDelegateM::Ice::Object
{
public:
};

}

}

namespace IceDelegateD
{

namespace loggerice
{

class LOG_ICE_API event : virtual public ::IceDelegate::loggerice::event,
                          virtual public ::IceDelegateD::Ice::Object
{
public:
};

}

}

namespace loggerice
{

class LOG_ICE_API event : virtual public ::Ice::Object
{
public:

    typedef eventPrx ProxyType;
    typedef eventPtr PointerType;

    event()
    {
    }

    event(::Ice::Int __ice_type, ::Ice::Long __ice_ts, ::Ice::Int __ice_srctype, ::Ice::Int __ice_srcid, ::Ice::Int __ice_kind, ::Ice::Long __ice_key, ::Ice::Long __ice_timeMs, ::Ice::Long __ice_threadId, ::Ice::Int __ice_regId) :
        type(__ice_type),
        ts(__ice_ts),
        srctype(__ice_srctype),
        srcid(__ice_srcid),
        kind(__ice_kind),
        key(__ice_key),
        timeMs(__ice_timeMs),
        threadId(__ice_threadId),
        regId(__ice_regId)
    {
    }

    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();


    static const ::Ice::ObjectFactoryPtr& ice_factory();

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif

public:

    ::Ice::Int type;

    ::Ice::Long ts;

    ::Ice::Int srctype;

    ::Ice::Int srcid;

    ::Ice::Int kind;

    ::Ice::Long key;

    ::Ice::Long timeMs;

    ::Ice::Long threadId;

    ::Ice::Int regId;

protected:

    virtual ~event() {}

    friend class event__staticInit;
};

class event__staticInit
{
public:

    ::loggerice::event _init;
};

static event__staticInit _event_init;

inline bool operator==(const event& l, const event& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const event& l, const event& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace loggerice
{

}

#endif
