// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `option_event.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef LOG_ICE_API_EXPORTS
#   define LOG_ICE_API_EXPORTS
#endif
#include <log_ice/ice/option_event.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __loggerice__optioneventif__sendevent_name = "sendevent";

}
#ifdef __SUNPRO_CC
class ICE_DECLSPEC_EXPORT IceProxy::loggerice::optionevent;
#endif
ICE_DECLSPEC_EXPORT ::IceProxy::Ice::Object* ::IceProxy::loggerice::upCast(::IceProxy::loggerice::optionevent* p) { return p; }

void
::IceProxy::loggerice::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::loggerice::optionevent>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::loggerice::optionevent;
        v->__copyFrom(proxy);
    }
}

const ::std::string&
IceProxy::loggerice::optionevent::ice_staticId()
{
    return ::loggerice::optionevent::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::loggerice::optionevent::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::loggerice::optionevent);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::loggerice::optionevent::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::loggerice::optionevent);
}

::IceProxy::Ice::Object*
IceProxy::loggerice::optionevent::__newInstance() const
{
    return new optionevent;
}
#ifdef __SUNPRO_CC
class ICE_DECLSPEC_EXPORT IceProxy::loggerice::optioneventif;
#endif
ICE_DECLSPEC_EXPORT ::IceProxy::Ice::Object* ::IceProxy::loggerice::upCast(::IceProxy::loggerice::optioneventif* p) { return p; }

void
::IceProxy::loggerice::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::loggerice::optioneventif>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::loggerice::optioneventif;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::loggerice::optioneventif::sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __loggerice__optioneventif__sendevent_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::loggerice::optioneventif* __del = dynamic_cast< ::IceDelegate::loggerice::optioneventif*>(__delBase.get());
            __del->sendevent(theevent, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::loggerice::optioneventif::begin_sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __loggerice__optioneventif__sendevent_name, __del, __cookie);
    try
    {
        __result->__prepare(__loggerice__optioneventif__sendevent_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(theevent);
        __os->writePendingObjects();
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::loggerice::optioneventif::end_sendevent(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __loggerice__optioneventif__sendevent_name);
}

const ::std::string&
IceProxy::loggerice::optioneventif::ice_staticId()
{
    return ::loggerice::optioneventif::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::loggerice::optioneventif::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::loggerice::optioneventif);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::loggerice::optioneventif::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::loggerice::optioneventif);
}

::IceProxy::Ice::Object*
IceProxy::loggerice::optioneventif::__newInstance() const
{
    return new optioneventif;
}

void
IceDelegateM::loggerice::optioneventif::sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __loggerice__optioneventif__sendevent_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(theevent);
        __os->writePendingObjects();
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::loggerice::optioneventif::sendevent(const ::loggerice::optioneventPtr& theevent, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::loggerice::optioneventPtr& __p_theevent, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_theevent(__p_theevent)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::loggerice::optioneventif* servant = dynamic_cast< ::loggerice::optioneventif*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->sendevent(_m_theevent, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::loggerice::optioneventPtr& _m_theevent;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __loggerice__optioneventif__sendevent_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(theevent, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

ICE_DECLSPEC_EXPORT ::Ice::Object* loggerice::upCast(::loggerice::optionevent* p) { return p; }
::Ice::ObjectPtr
loggerice::optionevent::ice_clone() const
{
    ::Ice::Object* __p = new optionevent(*this);
    return __p;
}

namespace
{
const ::std::string __loggerice__optionevent_ids[3] =
{
    "::Ice::Object",
    "::loggerice::event",
    "::loggerice::optionevent"
};

}

bool
loggerice::optionevent::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__loggerice__optionevent_ids, __loggerice__optionevent_ids + 3, _s);
}

::std::vector< ::std::string>
loggerice::optionevent::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__loggerice__optionevent_ids[0], &__loggerice__optionevent_ids[3]);
}

const ::std::string&
loggerice::optionevent::ice_id(const ::Ice::Current&) const
{
    return __loggerice__optionevent_ids[2];
}

const ::std::string&
loggerice::optionevent::ice_staticId()
{
    return __loggerice__optionevent_ids[2];
}

void
loggerice::optionevent::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, false);
    __os->write(subType);
    __os->write(value);
    __os->write(name);
    __os->write(strVal);
    __os->endWriteSlice();
    ::loggerice::event::__writeImpl(__os);
}

void
loggerice::optionevent::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(subType);
    __is->read(value);
    __is->read(name);
    __is->read(strVal);
    __is->endReadSlice();
    ::loggerice::event::__readImpl(__is);
}

namespace
{

class __F__loggerice__optionevent : public ::Ice::ObjectFactory
{
public:
#ifndef NDEBUG
virtual ::Ice::ObjectPtr
    create(const ::std::string& type)
#else
virtual ::Ice::ObjectPtr
    create(const ::std::string&)
#endif
    {
        assert(type == ::loggerice::optionevent::ice_staticId());
        return new ::loggerice::optionevent;
    }

    virtual void
    destroy()
    {
    }
};
const ::Ice::ObjectFactoryPtr __F__loggerice__optionevent_Ptr = new __F__loggerice__optionevent;

class __F__loggerice__optionevent__Init
{
public:

    __F__loggerice__optionevent__Init()
    {
        ::IceInternal::factoryTable->addObjectFactory(::loggerice::optionevent::ice_staticId(), __F__loggerice__optionevent_Ptr);
    }

    ~__F__loggerice__optionevent__Init()
    {
        ::IceInternal::factoryTable->removeObjectFactory(::loggerice::optionevent::ice_staticId());
    }
};

const __F__loggerice__optionevent__Init __F__loggerice__optionevent__i;

}

const ::Ice::ObjectFactoryPtr&
loggerice::optionevent::ice_factory()
{
    return __F__loggerice__optionevent_Ptr;
}

void ICE_DECLSPEC_EXPORT 
loggerice::__patch(optioneventPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::loggerice::optioneventPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::loggerice::optionevent::ice_staticId(), v);
    }
}

ICE_DECLSPEC_EXPORT ::Ice::Object* loggerice::upCast(::loggerice::optioneventif* p) { return p; }

namespace
{
const ::std::string __loggerice__optioneventif_ids[2] =
{
    "::Ice::Object",
    "::loggerice::optioneventif"
};

}

bool
loggerice::optioneventif::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__loggerice__optioneventif_ids, __loggerice__optioneventif_ids + 2, _s);
}

::std::vector< ::std::string>
loggerice::optioneventif::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__loggerice__optioneventif_ids[0], &__loggerice__optioneventif_ids[2]);
}

const ::std::string&
loggerice::optioneventif::ice_id(const ::Ice::Current&) const
{
    return __loggerice__optioneventif_ids[1];
}

const ::std::string&
loggerice::optioneventif::ice_staticId()
{
    return __loggerice__optioneventif_ids[1];
}

::Ice::DispatchStatus
loggerice::optioneventif::___sendevent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::loggerice::optioneventPtr theevent;
    __is->read(theevent);
    __is->readPendingObjects();
    __inS.endReadParams();
    sendevent(theevent, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __loggerice__optioneventif_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendevent"
};

}

::Ice::DispatchStatus
loggerice::optioneventif::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__loggerice__optioneventif_all, __loggerice__optioneventif_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __loggerice__optioneventif_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___sendevent(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
loggerice::optioneventif::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
loggerice::optioneventif::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void ICE_DECLSPEC_EXPORT 
loggerice::__patch(optioneventifPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::loggerice::optioneventifPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::loggerice::optioneventif::ice_staticId(), v);
    }
}
